### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by antonio-tomac** [martintomac/kafka-delayed-producer#1]
#### Issue 1
What about nullable record value in [DelayedRecord](https://github.com/martintomac/kafka-delayed-producer/blob/2439e7b2829552754225232ab060a002976b7e93/kafka-delayed-producer-core/src/main/kotlin/com/github/martintomac/kafkadelayedproducer/DelayedProducer.kt#L9)? And all other such cases where `V : Any` is used

#### Issue 2
This [Durations](https://github.com/martintomac/kafka-delayed-producer/blob/master/kafka-delayed-producer-core/src/main/kotlin/com/github/martintomac/kafkadelayedproducer/Durations.kt) utility
 - consider if it maybe pollutes any project which includes this lib? since hose are extensions on commonly used primitives
 - why is `Double.millis` extension omitted?

#### Issue 3
How about [returning](https://github.com/martintomac/kafka-delayed-producer/blob/2439e7b2829552754225232ab060a002976b7e93/kafka-delayed-producer-core/src/main/kotlin/com/github/martintomac/kafkadelayedproducer/DelayedProducer.kt#L16) `CompletableFuture` instead of `Future`

#### Issue 4
Consider ErrorHandler making async, especially to avoid usage of [Thread.sleep](https://github.com/martintomac/kafka-delayed-producer/blob/2439e7b2829552754225232ab060a002976b7e93/kafka-delayed-producer-core/src/main/kotlin/com/github/martintomac/kafkadelayedproducer/ErrorHandler.kt#L31).
Handling failed send [one by one](https://github.com/martintomac/kafka-delayed-producer/blob/2439e7b2829552754225232ab060a002976b7e93/kafka-delayed-producer-core/src/main/kotlin/com/github/martintomac/kafkadelayedproducer/KafkaDelayedProducer.kt#L107-L113) in blocking way will perform poorly.
`RetryingErrorHandler` should check the [type of exception](https://github.com/martintomac/kafka-delayed-producer/blob/2439e7b2829552754225232ab060a002976b7e93/kafka-delayed-producer-core/src/main/kotlin/com/github/martintomac/kafkadelayedproducer/ErrorHandler.kt#L22) and perform retry only if it is a [RetriableException](https://kafka.apache.org/26/javadoc/org/apache/kafka/common/errors/RetriableException.html) or maybe expose configurable way to let user decide what to retry and what should fail immediately.
Also, there should be some way to avoid infinite retrying and expose some way to pass hard failures (the ones we gave up on retrying) as _dead letter stream_. Using reference to `Future` returned to client might be a way but it would also mean that client code will need to keep track of all references and handle failed ones.

#### Issue 5
Do we really need [`producer`](https://github.com/martintomac/kafka-delayed-producer/blob/2439e7b2829552754225232ab060a002976b7e93/kafka-delayed-producer-core/src/main/kotlin/com/github/martintomac/kafkadelayedproducer/ErrorHandler.kt#L13) as an argument? 
Might be better to remove it and making it as field in `RetryingErrorrHandler` instead. 
Because, one might have custom ErrorHandler which stores records in DB or whatever.

#### Issue 6
Poll timeout and batch size of [poll](https://github.com/martintomac/kafka-delayed-producer/blob/2439e7b2829552754225232ab060a002976b7e93/kafka-delayed-producer-core/src/main/kotlin/com/github/martintomac/kafkadelayedproducer/KafkaDelayedProducer.kt#L92) should be configurable by user

#### Issue 7
Memory footprint:
- even though there is option to use custom [Reference](https://github.com/martintomac/kafka-delayed-producer/blob/2439e7b2829552754225232ab060a002976b7e93/kafka-delayed-producer-core/src/main/kotlin/com/github/martintomac/kafkadelayedproducer/Reference.kt#L3) which might store records on disk. There is still risk of overwhelming the heap by having huge amount of delayed messages in a [DelayQueue](https://github.com/martintomac/kafka-delayed-producer/blob/2439e7b2829552754225232ab060a002976b7e93/kafka-delayed-producer-core/src/main/kotlin/com/github/martintomac/kafkadelayedproducer/KafkaDelayedProducer.kt#L29) where each one of them holds reference to `DelayedRecordSendTask` which itself will use `12 + 3 * 8 = 36 bytes` 
-  let assume we have 1000msg/sec rate and delay each 8hrs. This will take up `~1GB` of heap assuming client does not hold `Future` references

#### Issue 8 (biggest issue)
How to handle JVM crash without data loss?
Even though we can use custom `Directory` to persist records, it is only persistence of records without persistence of scheduled tasks.
 - Let's consider use case when this lib is used in service which itself is a kafka consumer which will read a topic(s) and produce to another with delay. The question is now when it's safe to do consumer commit once message is submitted for delayed send? One option is to keep track for completion of `Future` of each record and make commits on completion while making sure to manually commit only up to largest offset such that all records with lower offset from same input topic partition completed their delayed delivery. This approach might be very tricky to implement by itself and especially hard if we consider what to do when consumer group re-balance happens, then you cannot commit to partitions which are no longer assigned to you.
 - As a user of lib I ask myself a question _"when I schedule record, do I need to wait for Future completion or is it safe to move on?"_

**Comment by martintomac** [comment]
**Issue 1**
I was not aware ProducerRecord with null value can is valid. I will make it nullable.

**Issue 2**
I am aware of the `Durations` utility file. I plan to do something about it later. Will probably remove it. It's here to ease initial development.

**Issue 3**
That will be probably one of the future improvements.

**Issue 4-5**
For now, I designed `ErrorHandler` as a send recovery mechanism due to Kafka unavailability or something similar. That's why I provide producer and block since no other records can be sent if Kafka is unavailable. Dead letter stream is technically possible with a changed topic but the format must be the same. `RetryingErrorHandler` is more like an example of what can be done with this. Error handling definitely needs more work. Currently `future` either is in progress or done and returns `RecordMetadata`. I'm not sure yet how would I incorporate that with dead letter stream or other DB.

**Issue 6**
I agree that should be configurable.

**Issue 7**
That is the design decision. I currently do not plan to keep tasks somewhere external. There may be some improvements to reduce these 36 bytes somewhat.

**Issue 8**
I gave it some thought and I delayed handling that issue internally for now. I gave a workaround possibility. Directory stores not only ProducerRecords but also delays and times of scheduling. With that, you could on startup iterate over your directory and schedule them with `DelayedProducer::send` again.

**Comment by antonio-tomac** [comment]
#### Issue 4-5
I would propose api design change so that signature for sending is as follows
```kotlin
package com.github.martintomac.kafkadelayedproducer

import org.apache.kafka.clients.producer.ProducerRecord
import org.apache.kafka.clients.producer.RecordMetadata
import java.io.Closeable
import java.time.Duration
import java.util.concurrent.CompletableFuture
import kotlin.Exception

interface DelayedProducer<K, V : Any> : Closeable {

    val numOfDelayedRecords: Int

    fun send(
        record: ProducerRecord<K, V>,
        afterDuration: Duration,
        callback: DelayedSendCallback
    )
    
}

fun <K, V : Any> DelayedProducer<K, V>.send(
    record: ProducerRecord<K, V>,
    afterDuration: Duration,
): Unit = send(record, afterDuration, DelayedSendCallback.NO_OP)

//if want to get response as future
fun <K, V : Any> DelayedProducer<K, V>.sendAsync(
    record: ProducerRecord<K, V>,
    afterDuration: Duration,
): CompletableFuture<RecordMetadata> {
    val future = CompletableFuture<RecordMetadata>()
    send(record, afterDuration, object : DelayedSendCallback {
        override fun onSent(recordMetadata: RecordMetadata) {
            future.complete(recordMetadata)
        }
        override fun onFailure(exception: Exception) {
            future.completeExceptionally(exception)
        }
        override fun onDiscarded(cancelCause: Exception) {
            future.completeExceptionally(cancelCause)
        }
    })
    return future
}

interface DelayedSendCallback {
    
    companion object {
        val NO_OP = object : DelayedSendCallback {}
    }

    /**
     * Record is successfully delivered to kafka
     */
    fun onSent(recordMetadata: RecordMetadata): Unit = Unit

    /**
     * Record was failed to be delivered with `exception` as failure reason
     */
    fun onFailure(exception: Exception): Unit = Unit

    /**
     * Record was failed to be delivered and discarded by `ErrorHandler`
     */
    fun onDiscarded(cancelCause: Exception): Unit = Unit
}
```

I'm making such proposal because I think that it's not needed for client to handle response using `Future` because future is meant to be holder for future response. And from client perspective I want to submit sending and forget about it without taking some future and keeping track wether it succeed or failed. And also I think that callback approach gives more flexibility with dead letter.

**Comment by martintomac** [comment]
@antonio-tomac I appreciate your proposal. I will most definitely experiment with it.
